default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: playlists_spotify_rails_development
  username: postgres
  password: 1amr00t
  host: localhost
  port: 5432

test:
  <<: *default
  database: playlists_spotify_rails_test
  username: postgres
  password: 1amr00t
  host: localhost
  port: 5432
  
production:
  <<: *default
  database: playlists_spotify_rails_production
  username: playlists_spotify_rails
  password: <%= ENV['PLAYLISTS_SPOTIFY_RAILS_DATABASE_PASSWORD'] %>
